### ISSUE TITLE
Don't complain about simple module names

### ISSUE THREAD

**Issue by ivarni** [angular/angular-hint#61]
I got this warning:

*The best practice for module names is to use lowerCamelCase. Check the name of "config"*

I'd argue that *config* already is lowerCamelCase. I don't feel it's very DRY to rename it to *configModule*.

**Comment by scottohara** [comment]
I agree that there needs to be a solution to prevent warnings about 3rd party modules.

With regard to the OPs comment about simple module names (e.g. `config`), I would assume that the warning is because the name doesn't pass the [modules should have a prefix rule](https://github.com/angular/angular-hint-modules#missing-namespace).

In which case it should be `xxConfig` (where `xx` is your prefix to distinguish it from someone else's `config` module)
